export const URL_MAP = {
  "/": "home",
  "/user-management": "user management",
  "/create-new-user": "create new user",
  "/activity-management": "activity management",
  "/activity-information": "activiy information",
  "/activity-modules": "activity module management",
  "/new-activity-module": "create new activiy module",
  "/packages": "package management",
  "/new-package": "create new package",
  "/position": "position management",
  "/departments": "department management",
  "/volunteer": "volunteer management",
  "/serviceprovider": "provider management",
  "/new-position": "create new position",
  "/new-department": "create new department",
  "/serviceprovider-information": "create new service provider",
  "/volunteer-information": "create new volunteer",
  "/execute-activity": "execute activity",
  "/activity-summary": "activity summary",
  "/invited-volunteer": "edit activity",
  "/invited-volunteer-report": "invited volunteer reports",
  "/volunteer-page": "invite volunteers",
  "/activity-report": "activity report"
};
